# Docker compose specification version is now obsolete:
# https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
#version: '3.9'

services:
  mysql:
    image: mysql:9.2.0
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: carctrl
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ADMIN}
    ports:
      - "3306:3306"
    volumes:
      - carctrl_mysql_volume:/var/lib/mysql
    networks:
      - carctrl_network
    restart: on-failure

  mariadb:
    image: mariadb:11.6.2
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MARIADB_DATABASE: carctrl
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - carctrl_mariadb_volume:/var/lib/mysql
    networks:
      - carctrl_network
    restart: on-failure

  postgres:
    image: postgres:17.3-alpine
    container_name: carctrl_keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_keycloak_volume:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: carctrl_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8443:8080"
    command:
      - start-dev

volumes:
  carctrl_mysql_volume:
  carctrl_mariadb_volume:
  postgres_keycloak_volume:

networks:
  carctrl_network:
