# Docker compose specification version is now obsolete:
# https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313
#version: '3.9'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: carctrl
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - carctrl_mysql_volume:/var/lib/mysql
    networks:
      - carctrl_network
    restart: on-failure

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MARIADB_DATABASE: carctrl
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - carctrl_mariadb_volume:/var/lib/mysql
    networks:
      - carctrl_network
    restart: on-failure

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${KEYCLOAK_DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - carctrl_keycloak_db_volume:/var/lib/postgresql/data
    restart: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    environment:
      # Deprecated according to Keycloak container logs
#      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      # Deprecated according to Keycloak container logs
#      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # Enables importing realms, without needing to remove "js" policies from the JSON export.
      # TODO: deprecated in version 18. Find workaround without needing to remove "js" policies
      #  https://github.com/keycloak/keycloak/issues/15869
#      JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8443:8080"
    volumes:
      - ./keycloak/car-control-realm.json:/opt/keycloak/data/import/car-control-realm.json
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"
    # OR
#    command:
#      - start-dev
#      - --import-realm
    depends_on:
      - postgres
    restart: on-failure

volumes:
  carctrl_mysql_volume:
  carctrl_mariadb_volume:
  carctrl_keycloak_db_volume:

networks:
  carctrl_network:
