"""V1 Initialize vehicle table

Revision ID: 10079527ed12
Revises: 
Create Date: 2025-02-13 07:32:01.431126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10079527ed12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('make', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'ELECTRIC', 'GASOLINE', name='fueltype'), nullable=False),
    sa.Column('door_count', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=32, scale=8), nullable=False),
    sa.Column('currency_code', sa.Enum('AUD', 'CAD', 'CHF', 'CNY', 'EUR', 'GBP', 'JPY', 'USD', name='currencycode'), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('door_count <= 256', name='ck_vehicle_door_count_max'),
    sa.CheckConstraint('door_count >= 0', name='ck_vehicle_door_count_min'),
    sa.CheckConstraint('length(description) >= 1', name='ck_vehicle_description_db_len'),
    sa.CheckConstraint('length(make) >= 1', name='ck_vehicle_make_min_length'),
    sa.CheckConstraint('length(model) >= 1', name='ck_vehicle_model_min_length'),
    sa.CheckConstraint('price >= 0', name='ck_vehicle_price_min'),
    sa.CheckConstraint('year >= 1900', name='ck_vehicle_year_min'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index('idx_vehicle_currency_code', ['currency_code'], unique=False)
        batch_op.create_index('idx_vehicle_make', ['make'], unique=False)
        batch_op.create_index('idx_vehicle_model', ['model'], unique=False)
        batch_op.create_index('idx_vehicle_price', ['price'], unique=False)
        batch_op.create_index('idx_vehicle_year', ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index('idx_vehicle_year')
        batch_op.drop_index('idx_vehicle_price')
        batch_op.drop_index('idx_vehicle_model')
        batch_op.drop_index('idx_vehicle_make')
        batch_op.drop_index('idx_vehicle_currency_code')

    op.drop_table('vehicle')
    # ### end Alembic commands ###
